source "https://rubygems.org"
gem "sinatra", :require => "sinatra/base"
gem "vzaar",:git => "https://github.com/revdan/vzaar.git"
gem "slim"
gem "oauth"
gem "httpclient"
gem "rushover"
gem "nokogiri"
gem "newrelic_rpm"
gem "sqlite3"
gem "datamapper"
gem "dm-sqlite-adapter"  